---
title: "December 6th Check in Meeting Costello"
author: "Juliette Verstaen"
date: "12/4/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Generalized Linear Model
```{r, echo = FALSE, message = FALSE}

suppressPackageStartupMessages({
  library(tidyverse)
  library(tidyr)
  library(here)
  library(ggplot2)
  library(dplyr)
  library(readxl)
  library(devtools)
  library(plotly)
  library(base)
  library(rio)
  library(plyr)
})


```

```{r, echo = FALSE, message = FALSE}

species_rightsbased <- read_csv("data/species_rightsbased_binary.csv")

upside_2018_updated <- readRDS("/GitHub/global_fisheries_managment/processed_data/upside_2018_updated.rds")

gdp_all <- read_csv("/GitHub/global_fisheries_managment/data/gpd.csv")


```


```{r, echo = FALSE, message = FALSE}

gdp <- filter(gdp_all, current_gdp != "NA")

join_gdp_rightsbased <- join(gdp, species_rightsbased, by = c("Country"), type = "full")

gdp_rightsbased <- filter(join_gdp_rightsbased, SpeciesCat != "NA" )

#write.csv(gdp_rightsbased, file = "gdp_rightsbased.csv")


```


```{r}

#gdp_rightsbased$SpeciesCat <- factor(gdp_rightsbased$SpeciesCat)

itq_glm <- glm(formula = i_right ~ current_gdp + SpeciesCat, family = "binomial", data = gdp_rightsbased)
itq_glm

summary(itq_glm)


```




#F/Fmsy vs. B/Bmsy for all fisheries

```{r, echo = FALSE, message = FALSE}

ITQ_projection <- readRDS("data/ITQ_projection.rds")

f_b_itq <- ITQ_projection %>%
  select("BvBmsy", "FvFmsy", "itq", "iq", "ivq") %>%
  filter( itq != "NA", iq != "NA", ivq != "NA")

#write.csv(f_b_itq, file = "f_b_itq.csv")
f_b_irights <- read_csv("data/f_b_irights.csv")


F_B_graph <- ggplot(data = f_b_irights, aes( x=BvBmsy, y=FvFmsy, colour= i_rights ))+
  geom_point()+
  labs(x = "B/Bmsy", y= "F/Fsmy") +
  theme_minimal()+
  theme(legend.title=element_blank())+
  ylim(-1, 22)+
  xlim(-.3, 3)+
  geom_hline(aes(yintercept=1))+
  geom_vline(aes(xintercept=1))

#F_B_graph
ggplotly(F_B_graph)

```

