---
title: "lab_notebook_2"
author: "Juliette Verstaen"
date: "12/7/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Loading packages
```{r}

suppressPackageStartupMessages({
  library(tidyverse)
  library(tidyr)
  library(here)
  library(ggplot2)
  library(dplyr)
  library(readxl)
  library(devtools)
  library(plotly)
  library(base)
  library(rio)
  library(plyr)
})

```



#Load Data
```{r}

#Corbet data: when countries began using RBFs
countries_ITQ <- read_excel("data/Countries_ITQ.xlsx")

#Upside data
projection_data <- readRDS("data/projection_data.rds")

#MPA data
MPA <- readRDS("data/WDPA_Nov2018.rds")

#RAMS
load("data/DBdata-model_fits_included.RData")

#number_species <- unique(stock$scientificname)
#341 different species

#cooperative data from "Conservation incentives and collective choices in cooperative fisheries" paper (Ovando et al 2013)
jc_coop <- read_csv("data/clean_cooperatives_data.csv")

#EDF turf data
edf_turf <- read_excel("data/EDF_TURF_data.xlsx")

```



```{r}


#Load Packages
suppressPackageStartupMessages({
  library(tidyverse)
  library(tidyr)
  library(here)
  library(ggplot2)
  library(dplyr)
  library(readxl)
  library(devtools)
  library(plotly)
  library(base)
  library(rio)
  library(plyr)
})


#Load Data
#Upside data
projection_data <- readRDS("data/projection_data.rds")

#RAMS
load("data/DBdata-model_fits_included.RData")

#Corbet data: when countries began using RBFs
countries_ITQ <- read_excel("data/Countries_ITQ.xlsx")



#RAM Data Tiddying
ram <- timeseries_values_views %>%
  select("stocklong", "year", "TBbest", "TCbest", "BdivBmsypref", "UdivUmsypref") %>%
  add_column("RAM")

colnames(ram) <- c( "CommName", "Year", "Biomass", "Catch", "BvBmsy", "FvFmsy", "DBase")



#Update Projection with RAM
projection_updated <- join(projection_data, ram, by = c("CommName", "Year"), type = "full")

#Merge Projection and ITQ
#seperate out IdOrig column for Projection Data
separate_projection <- projection_updated %>% separate(IdOrig, c("agency", "stock", "t0", "tf", "data_enterer"))

head(separate_projection, 10)

#reunite just the two parts we care about: agency and stock
unite_projection <- separate_projection %>% unite(assess_id_short, agency, stock, sep = "-")

#simplifying Countries ITQ with unique columns to prepare to merge
countries_ITQ_simple <- select(countries_ITQ, "assess_id_short", "year", "yearitq", "region_id", "idnumber", "harvest_fb", "itq_now", "iq", "itq", "ivq", "coop", "communityquota", "turf", "individualeffort", "iteq", "totalappliedeffort", "producerorg", "aquaculture", "programstart")

#rename year to be capitalized to merge with projection data
colnames(countries_ITQ_simple) <- c("assess_id_short", "Year", "yearitq", "region_id", "idnumber", "harvest_fb", "itq_now", "iq", "itq", "ivq", "coop", "communityquota", "turf", "individualeffort", "iteq", "totalappliedeffort", "producerorg", "aquaculture", "programstart")

ITQ_projection_merge <- merge(unite_projection, countries_ITQ_simple, by = c("assess_id_short", "Year"), all = TRUE)

#cleaning it up
ITQ_projection <- ITQ_projection_merge %>% unite(IdOrig, assess_id_short, t0, tf, data_enterer, sep = "-")

########
ITQ_projection_merge_different <- join(unite_projection, countries_ITQ_simple, by = c("assess_id_short", "Year"), type= "full")

ITQ_projection_different <- ITQ_projection_merge_different %>% unite(IdOrig, assess_id_short, t0, tf, data_enterer, sep = "-")

unique(ITQ_projection$itq)
unique(ITQ_projection_different$itq)


```

