---
title: "Updating Projection Data and Merging with ITQ"
author: "Juliette Verstaen"
date: "November 11, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Load Packages

```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(tidyr)
  library(here)
  library(ggplot2)
  library(dplyr)
  library(readxl)
  library(devtools)
  library(plotly)
  library(base)
  library(rio)
  library(plyr)
})
```


#Load Data
```{r}

#Upside data
projection_data <- readRDS("data/projection_data.rds")

#RAMS
load("data/DBdata-model_fits_included.RData")

#Corbet data: when countries began using RBFs
countries_ITQ <- read_excel("data/Countries_ITQ.xlsx")
```

#RAM Data Tiddying
```{r}
ram <- timeseries_values_views %>%
  select("stocklong", "year", "TBbest", "TCbest", "BdivBmsypref", "UdivUmsypref") %>%
  add_column("RAM")

colnames(ram) <- c( "CommName", "Year", "Biomass", "Catch", "BvBmsy", "FvFmsy", "DBase")
```

#Updata Projection with RAM
```{r}
projection_updated <- join(projection_data, ram, by = c("CommName", "Year"), type = "full")
```

#Merge Projection and ITQ
```{r}

#seperate out IdOrig column for Projection Data
separate_projection <- projection_updated %>% separate(IdOrig, c("agency", "stock", "t0", "tf", "data_enterer"))
    ###unsure what the last column actually is, double check

head(separate_projection, 10)

#reunite just the two parts we care about: agency and stock
unite_projection <- separate_projection %>% unite(assess_id_short, agency, stock, sep = "-")

#simplifying Countries ITQ with unique columns to prepare to merge
countries_ITQ_simple <- select(countries_ITQ, "assess_id_short", "year", "yearitq", "region_id", "idnumber", "harvest_fb", "itq_now", "iq", "itq", "ivq", "coop", "communityquota", "turf", "individualeffort", "iteq", "totalappliedeffort", "producerorg", "aquaculture", "programstart")

#rename year to be capitalized to merge with projection data
colnames(countries_ITQ_simple) <- c("assess_id_short", "Year", "yearitq", "region_id", "idnumber", "harvest_fb", "itq_now", "iq", "itq", "ivq", "coop", "communityquota", "turf", "individualeffort", "iteq", "totalappliedeffort", "producerorg", "aquaculture", "programstart")


ITQ_projection_merge <- merge(unite_projection, countries_ITQ_simple, by = c("assess_id_short", "Year"), all = TRUE)


#cleaning it up
ITQ_projection <- ITQ_projection_merge %>% unite(IdOrig, assess_id_short, t0, tf, data_enterer, sep = "-")
```


#Total number of species with stocks
#Number of stocks with ITQs implemented
```{r}
IdOrig <- unique(ITQ_projection$IdOrig)
IdOrig
#337 species total

ITQ_projection_implemented <- filter(ITQ_projection, programstart != "NA")

IdOrig_implemented <- unique(ITQ_projection_implemented$IdOrig)
IdOrig_implemented
#115 species with ITQ implemented
```



